### ISSUE TITLE
Allow optional client_timeout argument on all StorageRouterClient calls

### ISSUE THREAD

**Issue by khenderick** [openvstorage/volumedriver#128]
Allow optional `client_timeout` argument on all `StorageRouterClient` calls. While this is currently already a possible argument in the constructor, a reasonable timeout differs from call to call. E.g. for some kind of info/statistics call a 2s timeout would be appropriate, but for calls like migrates or truncates a longer timeout might be required.

**Comment by JeffreyDevloo** [comment]
### Information
After troubleshooting with @khenderick as to why the OVS-Workers just hang, I was referred to this ticket.
As he states, you can specify a timeout on the constructor of the client but to find a reasonable timeout to fit all the calls to the volumedriver is a terrible idea:
- Small calls could hang for potentially hours
- Long calls could be interrupted

### Current issue
When the node goes down in the cluster where all vpools were originally created, all remaining ovs-workers will hang, causing the rabbitmq queue to just keep heaping up.

What this means is that Framework cannot orchestrate any work during this downtime. Any webapi calls that require a task (creation of an object, scrubbing, calculating safety, fetching statistics, ...) will just be added to the queue and not be executed.

This is a severe issue in my eyes. Most consumers use the API to manipulate OVS as they like. Furthermore the GUI is the go-to location to verify if there any problems. (listing nodes would not work anymore due to this issue)

### Temporary solution
The only option to escape the loophole is by killing the process.
Restarting the process via restart ovs-workers will also hang.
The python runtime is completely stuck and will not respond to any signals. This is expected at this point as the python api of the volumedriver relies on the c++ code, which can't be interrupted by the api.

**Comment by matthiasdeblock** [comment]
Related issue discovered on a GIG environment:
```
2016-11-16 10:10:11 37500 +0100 - stor-201.be-gen8-1 - 11140/140291958736368 - dal/hybrid - 71 - ERROR - Error loading statistics_volume from e9f8530b-99bf-44a8-b5ba-b2b4551c8ce0: Throw location unknown (consider using BOOST_T
HROW_EXCEPTION)
Dynamic exception type: volumedriverfs::ObjectNotRegisteredException
std::exception::what: std::exception
[volumedriverfs::tag_volume_id*] = e9f8530b-99bf-44a8-b5ba-b2b4551c8ce0
```

**Comment by redlicha** [comment]
@matthiasdeblock , this is *not* related: it indicates that a mgmt call failed because the volume it was directed at was not there (anymore).

**Comment by matthiasdeblock** [comment]
My previous post wasn't correct, the message below has something to do with the timeout. According to @redlicha the only thing here is to debate if whether that timeout was maybe too long or too short.
```
2016-11-16 10:49:50 21400 +0100 - stor-201.be-gen8-1 - 9697/139934829798896 - dal/hybrid - 4 - ERROR - Error loading statistics_node from vmstord947zVGKa65qkq9n: failed to send XMLRPC request volumeDriverPerformanceCounters
```

**Comment by saelbrec** [comment]
Updated the ticket to milestone Fargo RC2 as 1 unresponsive volumedriver makes all framework calls to take ages. 
The only workaround to release the mangement calls and interface is shutting down the affected volumedriver. But without an interface one needs to look under the hood to identify the malfunctioning volumedriver instance.

**Comment by khenderick** [comment]
@saelbrec, @wimpers, this adds a dependency from framework to a specific version of the volumedriver. This introduces a possible issue with the framework being updated before the volumedriver, making calls with a parameter that doesn't yet exists. Can you choose one of these possible solutions:
* Fix #1253
* Write some new wrapper around the storagedriver client that can cope with such changes (e.g. the framework makes a call with the timeout, and if the version isn't high enough, it doesn't pass this timeout through)
* Don't do anything and expect users to first update the volumedriver

**Comment by pploegaert** [comment]
param used in fwk code is: req_timeout_secs

**Comment by pploegaert** [comment]
VALIDATION OK:
- 3 node setup
- 1 node poweroff
- list_volumes on vp object times out first time at +- 90seconds:
2017-02-21 10:30:49 98100 +0100 - e187-2 - 56540/140496657241856 - extensions/pyrakoon_client - 4 - WARNING - Arakoon call sequence took 92.54s
- subsequent: vp = VPoolList.get_vpools()[0] does succeed
- vp.storagedriver_client.list_volumes()
Out[7]: 
['119ad71b-26f4-4e7c-83fd-7f5f3f57b80c',
 '5ba01a67-4be4-448a-9bad-6e09e16a399b',
 '5e329c29-f410-4c9f-a7d3-275b80a82d63',
 'ca780b2f-7899-450f-90f0-d802d9b10b1d']
