### ISSUE TITLE
Edge HA needs locality knowledge in multi-dc vpool setups

### ISSUE THREAD

**Issue by saelbrec** [openvstorage/volumedriver#179]
In a multi datacenter cluster setup where the vpool stretches across different datacenters the Edge HA random selection of a new volumedriver connection endpoint in case of failure can result in cross datacenter connections. This is sub-awesome and in most cases -depending on the network latency- not the desired behaviour as it can possibly have a big impact on performance.
In case Edge/volumedriver have locality knowledge they can take better decisions on their failover connection endpoints. Optionally it might even be desirable to let the user configure if cross datacenter failover should be allowed after all local possibilities are exhausted.

**Comment by wimpers** [comment]
In case the voldrv know about locality, we might be able to support live migration across the DCs with first invoking the API. In case the VM is moved and IO comes through a voldrv which is outside the HA locality, allow automated stealing.

**Comment by wimpers** [comment]
> Optionally it might even be desirable to let the user configure if cross datacenter failover should be allowed after all local possibilities are exhausted.

I would say yes. First select a Storage Router which has the same Domain tag, if no Storage Routers available with the same Domain tag, select the Recovery Domain tag.

**Comment by wimpers** [comment]
One remark:, in some cases you will have that DC 1 has DC2 as recovery domain and vice versa. So if Edge HA fails over to the other DC, no DTL will be set as all the Storage Routers in the recovery domain will be down.

**Comment by redlicha** [comment]
Idea: Represent the topology as a (fully connected) graph with weighted edges. When a client requests the list of cluster members from a volumedriver, all adjacent vertices and the cost to get there are reported.
Based on these costs, clients can decide which node to failover to, using the current random choice strategy in case of multiple neighbours with the same cost.
The list of neighbours is  filtered (on the server side) based on the cost to prevent failover to different or distant DCs. Initially the filtering will be done per volumedriver instance (i.e. all clients connected to a volumedriver will see the same list of neighbours).

**Comment by redlicha** [comment]
After discussion with @cnanakos: the client/server protocol change can be avoided by modifying the client to pick the failover target *in order* from the list of neighbours instead of picking a random one (currently,  or looking at a yet to be introduced `Cost`).

**Comment by khenderick** [comment]
@redlicha, makes sense. 

The new argument to the ```ClusterNodeConfig``` will be a list which contains all costs for the other nodes from that volumedriver's viewpoint. If I don't add a given other node to the list, will the cost be assumed to be infinite, or 0?

I assume this will be dynamically reconfigurable by the ```set_node_configs```?

**Comment by redlicha** [comment]
@khenderick: tentatively (PR will follow soon):
* the `Distance` will be represented by a `uint32_t` with the following semantics: `0` = very close, `2**32-1` = very far away
* the neighbours of a node are represented with a dict `NodeId -> Distance` (`NodeId = str`) instead of a list (rules out duplicate nodes), if a node is absent there this indicates that there is no connection to it / it's infinitely far away
* the `ClusterNodeConfig` ctor actually takes an *optional* dict: `None` maintains the current behaviour, i.e. all nodes are assumed to be reachable with a cost of 0, `{}` -> all nodes are infinitely far away
* filtering: with the above outlined semantics, the `max_neighbour_distance` will use a default value of `2**32 - 1`
* modifications to the topology indeed have to be done with `set_node_configs`, i.e. the complete cluster config always needs to be specified in one go (and volumedrivers need to be notified if cluster members are added / removed via `update_cluster_node_configs`). So no change from currnet behaviour there.

Final interface description will end up in the PR.

**Comment by wimpers** [comment]
@redlicha is there something build-in to prevent a migration to happen if the cost is above a certain threshold? If there are only nodes with a 2**32-1  you might decide not to move.

**Comment by redlicha** [comment]
Yes - the configurable mentioned above which ended up being called `network_interface/network_max_neighbour_distance` in the actual implementation. Any node with a distance >= that value is hidden from clients. Only nodes with a distance < that value are reported to clients  in order of preference (shortest distance first, order of equidistant nodes is randomized on the server side).

**Comment by redlicha** [comment]
@khenderick : NB: when upgrading existing clusters to a version with this feature, all cluster members need to be updated first before making changes to the registry (adding distance information).

**Comment by khenderick** [comment]
@wimpers, the above upgrade requirement basically adds a dependency to openvstorage/framework#1224

**Comment by wimpers** [comment]
@redlicha why can't the voldrv deal with that additional parameter in the config. Can't it just ignore it?

**Comment by redlicha** [comment]
It's not about the additional parameter in the config - it's about the additional topology information in the ClusterRegistry which is serialized with boost::serialization. Due to the current representation of the serialized data structure (everything's read from a stream, skipping unknown/newly introduced fields is not trivial) the above approach is easiest. In this special instance we could work around it by adding another layer of indirection for the serialization of the topology info. In general it will however be handy to have the escape hatch of first updating all voldrvs (to introduce new functionality) and then only afterwards the fwk (to enable this new functionality).

**Comment by wimpers** [comment]
@redlicha updating the voldrv before the framework is something we should use  as a last resort but we should be able to run mixed versions. Assume you have a large environment, I will not be able to guarantee for 100% of the cases that all voldrv will be there. I'll create a [FR](https://github.com/openvstorage/volumedriver/issues/191) for allowing new, to be skipped fields.

**Comment by pploegaert** [comment]
Validation continued in:
https://github.com/openvstorage/integrationtests/issues/435

**Comment by JeffreyDevloo** [comment]
Opening as it has not been validated yet.

**Comment by saelbrec** [comment]
@JeffreyDevloo , 
I think this has been validated, right?
I remember @kinvaris running into the situation where HA was refusing to move volume to a node from another domain.
If you are still thinking of other validation tests, than please readd the 'state_verification' label, otherwise please close.

**Comment by kinvaris** [comment]
Recently we've created 2 tests:
1. The HA test: This tests the automated HA for multiple vdisks. In this test there are no domains used. This test is still being validated/reviewed but is working.

2. The DTL test: This tests if written data can survive through the DTL with multiple vdisks. In this test we've observed that vdisk migration between multiple datacenter is not possbile. This is by design through the framework. But if we have 2 nodes inside the same domain, the automated HA does work.
