### ISSUE TITLE
Snapshotting a non-running volume results in maxredirect error

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/volumedriver#224]
### Problem description
Whilest investigation why certain volumes did not have any snapshots on one of our environments, I came across the following error:

```
In [7]: vdisk.storagedriver_client.create_snapshot(str(vdisk.volume_id))
---------------------------------------------------------------------------
MaxRedirectsExceededException             Traceback (most recent call last)
<ipython-input-7-40e6963c2a69> in <module>()
----> 1 vdisk.storagedriver_client.create_snapshot(str(vdisk.volume_id))

MaxRedirectsExceededException: snapshotCreate 
```
This disk had the dtl_status unknown and was not running (failed to start due to full asds)

The issue is that I do not expect a MaxRedirectException but a NotRunningException or something like that.

**Comment by redlicha** [comment]
At the moment this is expected behaviour.
Background: there's a race between a mgmt call locating an object and the object migrating between nodes:
* mgmt call C is executed on node X, object is not running there -> object location is looked up (node Y), C is redirect to Y
* Y is moved to node Z
* C is executed on Y

. The number of redirects is limited, so if an object cannot be found it's not clear whether it was moved away of if it's not running, so for the moment the `MaxRedirectsExceededException` is raised in both cases. IOW this is independent of the actual mgmt call, other calls like `info_volume` show the same behaviour.

Providing better feedback / a distinct exception might be possible.

**Comment by JeffreyDevloo** [comment]
Closing it down as it is expected behaviour.
